//
//  UserListInteractor.swift
//  CoredataPOC
//
//  Created by Wipro on 12/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListBusinessLogic
{
  func doSomething(request: UserList.Something.Request)
  func getSlipArray(tag:Int) -> [String]
  func getSlipArrayCount(tag:Int) -> Int
  func getSlipTitle(tag:Int) -> String
}

protocol UserListDataStore
{
  //var name: String { get set }
}

class UserListInteractor: UserListBusinessLogic, UserListDataStore
{
  var presenter: UserListPresentationLogic?
  var worker: UserListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UserList.Something.Request)
  {
    worker = UserListWorker()
    worker?.doSomeWork()
    
    CoreDataManager.sharedInstance.fetchList(completionHandler: { (responce) -> Void in
        let response = UserList.Something.Response(orders: responce as! [CUsers])

        self.presenter?.presentSomething(response: response)
    })
    
    //let response = UserList.Something.Response()
   // presenter?.presentSomething(response: response)
    
    
  }
    
    func getSlipArray(tag:Int) -> [String] {
        let slipArray:[String]!
              if (tag == 1) {
                  slipArray = ["item1","item2","item3","item4","item5","item6","item7","item8","item9","item10","item11","item12","item13","item14","item15","item16","item17","item18","item19","item20","item21","item22","item23","item24","item25","item26","item27","item28","item29","item30"]
              }else if (tag == 2){
                  slipArray = ["item1","item2","item3","item4","item5"]
              }else if (tag == 3){
                  slipArray = ["item1","item2","item3","item4","item5","item6","item7","item8","item9","item10"]
              }else{
                  slipArray = ["checking"]
              }
          return slipArray
          }
          
          func getSlipArrayCount(tag:Int) -> Int {
            let slipArray:[String]!
              if (tag == 1) {
                  slipArray = ["item1","item2","item3","item4","item5","item6","item7","item8","item9","item10","item11","item12","item13","item14","item15","item16","item17","item18","item19","item20","item21","item22","item23","item24","item25","item26","item27","item28","item29","item30"]
              }else if (tag == 2){
                  slipArray = ["item1","item2","item3","item4","item5"]
              }else if (tag == 3){
                  slipArray = ["item1","item2","item3","item4","item5","item6","item7","item8","item9","item10"]
              }else{
                  slipArray = ["checking"]
              }
              return slipArray.count
          }
          
          func getSlipTitle(tag:Int) -> String {
              let slipTitle:String!
              
              if (tag == 1) {
                  slipTitle = "Table1"
              }else if (tag == 2){
                 slipTitle = "Table2"
              }else if (tag == 3){
                  slipTitle = "Table3"
              }else{
                  slipTitle = "default"
              }
              return slipTitle
          }
}
